version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crudapp
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crudapp-network

  backend:
    build: ./backend
    container_name: backend-container
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: user_password
      DB_NAME: crudapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - crudapp-network

networks:
  crudapp-network:
    driver: bridge

volumes:
  db_data:
